### ISSUE TITLE
6 cams with navigation when script is running

### ISSUE THREAD

**Issue by Shigoru** [LS80/xbmc.repo.leopold#1]
Hi LS80
is it possible to make a version with 6cams. As Overlay with no black.png. This should not be the problem.
But with the posibility to navigate when the script is running?

I would like to integrate the addon into a skin as a main navigation point like movies names "Security".
The navigation is important so that i can start a fullscreen stream of each cam shown.

Do you speak german? I am working on this since a while.
http://www.kodinerds.net/index.php/Thread/32671-Securitycams-Webcams-als-Hauptmen%C3%BCpunkt-mit-Livestream/?pageNo=1

Would be nice to hear from you.
Shigoru

**Comment by Shigoru** [comment]
Hi
i already found out what to change to get 6 cams running in overlay with no black background.
Could you help me to get a navigation running?
Cu
Shigoru

**Comment by LS80** [comment]
To navigate the menus can you just press "back"?
Let's take the discussion to http://forum.kodi.tv/showthread.php?tid=218815
